name: Push to Remote Branch

on:
  push:
    branches:
      - main

jobs:
  push-to-remote-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to Remote
        run: |
          git config --global user.name 'Truls'
          git config --global user.email 'truls.vidnes@hotmail.no'
          git remote add public https://github.com/trulsbv/Football-Public
          git push public main:main
